// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrWcTr_piSsZUGNkwpI_PzlihLqTZg7k4',
    appId: '1:1012390098074:web:272fe2de59c2e27ca79b23',
    messagingSenderId: '1012390098074',
    projectId: 'ffs-example',
    authDomain: 'ffs-example.firebaseapp.com',
    storageBucket: 'ffs-example.appspot.com',
    measurementId: 'G-R0FVB3JXPB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtQJXJzdBQFGZSpQXYez42YOJTyHPpZpk',
    appId: '1:1012390098074:android:ae1a5b7706e06b0da79b23',
    messagingSenderId: '1012390098074',
    projectId: 'ffs-example',
    storageBucket: 'ffs-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGADOvxPb7iFN8OWv1-oAyEooIQx3QAME',
    appId: '1:1012390098074:ios:29701767030e4cb4a79b23',
    messagingSenderId: '1012390098074',
    projectId: 'ffs-example',
    storageBucket: 'ffs-example.appspot.com',
    iosBundleId: 'com.example.fsfExample',
  );
}
